name: bank_attrition_env
channels:
- conda-forge
dependencies:
- python=3.12.7
- pip
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - dagshub