channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - dagshub==0.5.1
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - matplotlib==3.8.4
  - seaborn==0.13.2
  - scipy==1.14.1
name: mlflow-env