channels:
- conda-forge
dependencies:
- python=3.12.6
- pip
- pip:
  - mlflow==2.19.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - matplotlib==3.8.4
  - seaborn==0.13.2
name: mlflow-env