channels:
- conda-forge
dependencies:
- python=3.12.6
- pip
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1 
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.4.2
  - scipy==1.14.1
name: mlflow-env