name: CI MLflow Training

on:
  workflow_dispatch:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci_training.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn scikit-learn mlflow 

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=https://dagshub.com/<username>/<repo>.mlflow" >> $GITHUB_ENV

      - name: Run mlflow project
        working-directory: MLProject
        run: python modelling_tuning.py

      - name: Get latest MLflow run_id
        id: get-run
        run: |
          echo "Fetching latest MLflow run ID..."
          RUN_ID=$(mlflow search-runs -n 1 -o start_time.desc --output json | jq -r '.[0].run_id')
          echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker Model
        run: |
          echo "Building Docker image from MLflow model..."
          mlflow models build-docker -m runs:/$MLFLOW_RUN_ID/model -n ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Upload model artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model
          path: MLProject/model/