name: CI MLflow Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn matplotlib seaborn

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local 

    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        echo "RUN_ID=$(ls -td mlruns/0/* | head -1 | cut -d'/' -f3)" >> $GITHUB_ENV

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: mlruns/0/${{ env.RUN_ID }}/artifacts/model/

    - name: Build Docker image
      run: |
        mlflow models build-docker -m runs:/${{ env.RUN_ID }}/model -n my-rf-model

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push Docker Image
      run: |
        docker tag my-rf-model ${{ secrets.DOCKER_USERNAME }}/my-rf-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-rf-model:latest