name: CI MLflow Training

on:
  workflow_dispatch:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci_training.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install dependencies via pip (fallback)
        run: pip install pandas numpy matplotlib seaborn scikit-learn mlflow dagshub

      - name: Run training script
        working-directory: MLProject
        run: python modelling_tuning.py
